repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Git
      - id: forbid-new-submodules

      # Files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace

      # Syntax
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-json

      # Code
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/akaihola/darker
    rev: v2.1.1
    hooks:
      - id: darker
        args: ["--check"]
        stages: [push]
      - id: darker
        stages: [commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
