name: 🧹 Darker

on:
  pull_request:
    branches:
      - main

jobs:
  darker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: akaihola/darker@1.7.3
        with:
          version: "1.7.3"
